name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.f40f645b-5489-457f-ae25-814e155bdec6}}
          heroku_app_name: "anonyzemusicbot" #Must be unique in Heroku
          heroku_email: "mbpkofjeeew@candassociates.com"
